name: Cancel Previous PR Workflows
on:
  workflow_run:
    workflows: ["Dependencies autoupdate", "Build Anomaly Detection App Container",  "Build Production Rust Code", "Build Rust CrossBuild", "Check Rust", "Check versioning", "Helm", "Tarpaulin Code Coverage", "Test K3s, Kubernetes, and MicroK8s"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
    - uses: styfle/cancel-workflow-action@0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}