name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  target: "x86_64-unknown-linux-gnu"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: My first step
      uses: actions/checkout@v3
    - name: install cargo-cross
      run: cargo install cross
    - name: Build
      run: CARGO_INCREMENTAL=0 PKG_CONFIG_ALLOW_CROSS=1 cross build  --release --target=${target};
    - name: Run tests
      run: CARGO_INCREMENTAL=0 PKG_CONFIG_ALLOW_CROSS=1 cross test  --release --target=${target}
